kind: Service
apiVersion: v1
metadata:
  name: spark-webui
  namespace: spark-cluster1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
  selector:
    component: spark-master
